live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "Iosevka"
style = "Regular"

[font.bold_italic]
family = "Iosevka"
style = "Medium Italic"

[font.italic]
family = "Iosevka"
style = "Light Italic"

[font.normal]
family = "Iosevka"
style = "Light"

[scrolling]
history = 10000

[window]
dynamic_padding = true
